id: I62163181
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:52:10.045995
last_modified: 2023-02-09 14:52:10.046113
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: zh
bases:
  601B:
    base_file: 601B.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
